"""Interactive chessboard camera calibration script.

Workflow:
1) Open camera index 1 by default.
2) Live preview first, press 'c' to confirm and continue.
3) A timestamped output directory is created for this run.
4) In capture mode:
   - Press Enter to capture a frame (only when chessboard is detected).
   - Press 'd' to delete last captured frame.
   - Press 'q' / Esc to finish and run calibration.
5) Save calibration outputs into the same timestamped directory.

It can auto-load dimensions from calibrate/chessboard_meta.json generated by calibrate/board.py.
"""

from __future__ import annotations

import argparse
import json
import platform
from datetime import datetime
from pathlib import Path
from typing import List, Optional, Tuple

import cv2
import numpy as np


PREVIEW_WINDOW = "Calibration2 - Preview"
CAPTURE_WINDOW = "Calibration2 - Capture"
UNDISTORT_WINDOW = "Calibration2 - Undistort Preview"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Interactive camera calibration with chessboard.")
    parser.add_argument("--camera-index", type=int, default=1, help="Camera index. Default: 1")
    parser.add_argument("--camera-id", type=str, default="1", help="Camera identifier for output folder naming. Default: 1")
    parser.add_argument("--squares-cols", type=int, default=None, help="Chessboard square count in width (e.g. 9)")
    parser.add_argument("--squares-rows", type=int, default=None, help="Chessboard square count in height (e.g. 6)")
    parser.add_argument(
        "--inner-cols",
        type=int,
        default=None,
        help="Chessboard inner corners in width (corners, not squares). Overrides --squares-cols.",
    )
    parser.add_argument(
        "--inner-rows",
        type=int,
        default=None,
        help="Chessboard inner corners in height (corners, not squares). Overrides --squares-rows.",
    )
    parser.add_argument(
        "--square-size",
        type=float,
        default=29.0,
        help="Square size in mm. Default: 29.0 (not overridden by meta).",
    )
    parser.add_argument("--min-samples", type=int, default=12, help="Minimum captures required. Default: 12")
    parser.add_argument("--width", type=int, default=1280, help="Requested frame width. <=0 keeps default")
    parser.add_argument("--height", type=int, default=720, help="Requested frame height. <=0 keeps default")
    parser.add_argument(
        "--board-meta",
        type=str,
        default=str(Path(__file__).resolve().parent / "chessboard_meta.json"),
        help="Path to board metadata JSON generated by board.py",
    )
    parser.add_argument("--no-meta", action="store_true", help="Ignore --board-meta even if file exists")
    parser.add_argument(
        "--output-root",
        type=str,
        default=None,
        help="Base output dir. Defaults to runs_chess_<camera_id>",
    )
    parser.add_argument("--show-undistorted", action="store_true", help="Show undistorted preview after calibration")
    return parser.parse_args()


def load_board_meta(meta_path: Path) -> Optional[dict]:
    if not meta_path.exists():
        return None
    try:
        data = json.loads(meta_path.read_text(encoding="utf-8"))
    except Exception:
        return None
    if data.get("board_type") != "chessboard":
        return None
    return data


def choose_effective_pattern(args: argparse.Namespace) -> Tuple[int, int, float, Optional[Path]]:
    default_inner_cols = 8
    default_inner_rows = 5
    default_square_size = 29.0

    inner_cols = default_inner_cols
    inner_rows = default_inner_rows
    square_size = default_square_size

    used_meta: Optional[Path] = None
    if not args.no_meta:
        meta_path = Path(args.board_meta)
        meta = load_board_meta(meta_path)
        if meta is not None:
            if "inner_corners_cols" in meta:
                inner_cols = int(meta["inner_corners_cols"])
            if "inner_corners_rows" in meta:
                inner_rows = int(meta["inner_corners_rows"])
            used_meta = meta_path

    # Square counts (grids) -> inner corner counts.
    if args.squares_cols is not None:
        inner_cols = int(args.squares_cols) - 1
    if args.squares_rows is not None:
        inner_rows = int(args.squares_rows) - 1

    # Explicit inner-corner args take highest priority.
    if args.inner_cols is not None:
        inner_cols = int(args.inner_cols)
    if args.inner_rows is not None:
        inner_rows = int(args.inner_rows)

    square_size = float(args.square_size)

    return inner_cols, inner_rows, square_size, used_meta


def camera_backend() -> Optional[int]:
    if platform.system().lower().startswith("win") and hasattr(cv2, "CAP_DSHOW"):
        return cv2.CAP_DSHOW
    return None


def open_camera(index: int, width: int, height: int) -> Optional[cv2.VideoCapture]:
    backend = camera_backend()
    cap = cv2.VideoCapture(index, backend) if backend is not None else cv2.VideoCapture(index)
    if not cap.isOpened():
        cap.release()
        return None

    if width > 0:
        cap.set(cv2.CAP_PROP_FRAME_WIDTH, width)
    if height > 0:
        cap.set(cv2.CAP_PROP_FRAME_HEIGHT, height)

    for _ in range(12):
        ok, frame = cap.read()
        if ok and frame is not None:
            return cap

    cap.release()
    return None


def create_run_dir(output_root: Path) -> Path:
    output_root.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = output_root / stamp
    run_dir.mkdir(parents=True, exist_ok=False)
    return run_dir


def draw_status(frame: np.ndarray, lines: List[str], color: Tuple[int, int, int]) -> np.ndarray:
    view = frame.copy()
    y = 28
    for line in lines:
        cv2.putText(view, line, (16, y), cv2.FONT_HERSHEY_SIMPLEX, 0.65, color, 2, cv2.LINE_AA)
        y += 28
    return view


def wait_for_confirm(cap: cv2.VideoCapture, camera_index: int) -> bool:
    while True:
        ok, frame = cap.read()
        if not ok or frame is None:
            frame = np.zeros((480, 640, 3), dtype=np.uint8)

        view = draw_status(
            frame,
            [
                f"Camera index: {camera_index}",
                "Press c to confirm this camera and start capture",
                "Press q or Esc to quit",
            ],
            (0, 255, 0),
        )
        cv2.imshow(PREVIEW_WINDOW, view)

        key = cv2.waitKey(1) & 0xFF
        if key == ord("c"):
            cv2.destroyWindow(PREVIEW_WINDOW)
            return True
        if key in (ord("q"), 27):
            cv2.destroyWindow(PREVIEW_WINDOW)
            return False


def find_chessboard(gray: np.ndarray, pattern_size: Tuple[int, int]) -> Tuple[bool, Optional[np.ndarray]]:
    if hasattr(cv2, "findChessboardCornersSB"):
        flags = cv2.CALIB_CB_EXHAUSTIVE | cv2.CALIB_CB_ACCURACY
        found, corners = cv2.findChessboardCornersSB(gray, pattern_size, flags=flags)
        if found:
            return True, corners

    flags = cv2.CALIB_CB_ADAPTIVE_THRESH | cv2.CALIB_CB_NORMALIZE_IMAGE
    found, corners = cv2.findChessboardCorners(gray, pattern_size, flags)
    if not found:
        return False, None

    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 1e-3)
    refined = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
    return True, refined


def capture_samples(
    cap: cv2.VideoCapture,
    run_dir: Path,
    pattern_size: Tuple[int, int],
    square_size: float,
) -> Tuple[List[np.ndarray], List[np.ndarray], Optional[Tuple[int, int]], List[Path]]:
    obj_template = np.zeros((pattern_size[0] * pattern_size[1], 3), dtype=np.float32)
    obj_template[:, :2] = np.mgrid[0 : pattern_size[0], 0 : pattern_size[1]].T.reshape(-1, 2)
    obj_template *= square_size

    object_points: List[np.ndarray] = []
    image_points: List[np.ndarray] = []
    image_size: Optional[Tuple[int, int]] = None
    saved_paths: List[Path] = []

    while True:
        ok, frame = cap.read()
        if not ok or frame is None:
            frame = np.zeros((480, 640, 3), dtype=np.uint8)

        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        found, corners = find_chessboard(gray, pattern_size)

        view = frame.copy()
        if found and corners is not None:
            cv2.drawChessboardCorners(view, pattern_size, corners, found)

        view = draw_status(
            view,
            [
                f"Captured images: {len(saved_paths)}",
                "Enter: capture current frame (requires chessboard detected)",
                "d: delete last capture   q/Esc: finish and calibrate",
                f"Chessboard detected: {'YES' if found else 'NO'}",
            ],
            (255, 255, 255),
        )

        cv2.imshow(CAPTURE_WINDOW, view)
        key = cv2.waitKey(1) & 0xFF

        if key in (ord("q"), 27):
            break

        if key == ord("d"):
            if saved_paths:
                last_path = saved_paths.pop()
                if last_path.exists():
                    last_path.unlink()
                object_points.pop()
                image_points.pop()
                print(f"[INFO] Deleted last capture: {last_path.name}")
            else:
                print("[INFO] No captured frame to delete.")
            continue

        if key in (10, 13):
            if not found or corners is None:
                print("[WARN] Chessboard not detected. Move board and try again.")
                continue

            image_size = (gray.shape[1], gray.shape[0])
            idx = len(saved_paths) + 1
            image_path = run_dir / f"image_{idx:03d}.png"
            cv2.imwrite(str(image_path), frame)

            saved_paths.append(image_path)
            object_points.append(obj_template.copy())
            image_points.append(corners.astype(np.float32))
            print(f"[INFO] Captured {image_path.name}")

    cv2.destroyWindow(CAPTURE_WINDOW)
    return object_points, image_points, image_size, saved_paths


def mean_reprojection_error(
    object_points: List[np.ndarray],
    image_points: List[np.ndarray],
    rvecs: List[np.ndarray],
    tvecs: List[np.ndarray],
    camera_matrix: np.ndarray,
    dist_coeffs: np.ndarray,
) -> float:
    total_error = 0.0
    for i, obj_pts in enumerate(object_points):
        projected, _ = cv2.projectPoints(obj_pts, rvecs[i], tvecs[i], camera_matrix, dist_coeffs)
        error = cv2.norm(image_points[i], projected, cv2.NORM_L2) / len(projected)
        total_error += float(error)
    return total_error / max(len(object_points), 1)


def calibrate_and_save(
    run_dir: Path,
    object_points: List[np.ndarray],
    image_points: List[np.ndarray],
    image_size: Tuple[int, int],
    camera_index: int,
    pattern_size: Tuple[int, int],
    square_size: float,
    used_meta: Optional[Path],
) -> Tuple[np.ndarray, np.ndarray]:
    rms, camera_matrix, dist_coeffs, rvecs, tvecs = cv2.calibrateCamera(
        object_points,
        image_points,
        image_size,
        None,
        None,
    )

    mean_error = mean_reprojection_error(
        object_points,
        image_points,
        rvecs,
        tvecs,
        camera_matrix,
        dist_coeffs,
    )

    result_json = {
        "camera_index": int(camera_index),
        "image_size": [int(image_size[0]), int(image_size[1])],
        "pattern_inner_cols": int(pattern_size[0]),
        "pattern_inner_rows": int(pattern_size[1]),
        "square_size_mm": float(square_size),
        "image_count": int(len(image_points)),
        "rms": float(rms),
        "mean_reprojection_error": float(mean_error),
        "camera_matrix": camera_matrix.tolist(),
        "dist_coeffs": dist_coeffs.tolist(),
        "board_meta_path": str(used_meta) if used_meta is not None else None,
    }

    json_path = run_dir / "calibration_result.json"
    json_path.write_text(json.dumps(result_json, indent=2), encoding="utf-8")

    npz_path = run_dir / "calibration_result.npz"
    np.savez(
        str(npz_path),
        camera_matrix=camera_matrix,
        dist_coeffs=dist_coeffs,
        image_size=np.array(image_size, dtype=np.int32),
        pattern_size=np.array(pattern_size, dtype=np.int32),
        square_size_mm=np.array([square_size], dtype=np.float32),
        rms=np.array([rms], dtype=np.float64),
        mean_reprojection_error=np.array([mean_error], dtype=np.float64),
    )

    print("\n[RESULT] Calibration finished.")
    print(f"[RESULT] RMS: {rms:.6f}")
    print(f"[RESULT] Mean reprojection error: {mean_error:.6f} px")
    if rms > 2.0:
        print("[WARN] RMS looks high; collect more diverse views and verify board dimensions.")
    print(f"[RESULT] Saved JSON: {json_path}")
    print(f"[RESULT] Saved NPZ : {npz_path}")

    return camera_matrix, dist_coeffs


def preview_undistortion(cap: cv2.VideoCapture, camera_matrix: np.ndarray, dist_coeffs: np.ndarray) -> None:
    ok, frame = cap.read()
    if not ok or frame is None:
        print("[WARN] Cannot open undistorted preview because no frame is available.")
        return

    h, w = frame.shape[:2]
    new_mtx, _ = cv2.getOptimalNewCameraMatrix(camera_matrix, dist_coeffs, (w, h), 1, (w, h))

    while True:
        ok, frame = cap.read()
        if not ok or frame is None:
            continue

        undistorted = cv2.undistort(frame, camera_matrix, dist_coeffs, None, new_mtx)
        merged = np.hstack([frame, undistorted])
        merged = draw_status(
            merged,
            ["Left: original   Right: undistorted", "Press q or Esc to close"],
            (255, 255, 255),
        )

        cv2.imshow(UNDISTORT_WINDOW, merged)
        key = cv2.waitKey(1) & 0xFF
        if key in (ord("q"), 27):
            break

    cv2.destroyWindow(UNDISTORT_WINDOW)


def main() -> int:
    args = parse_args()

    if args.squares_cols is not None and args.squares_cols <= 1:
        print("[ERROR] squares-cols must be >= 2")
        return 1
    if args.squares_rows is not None and args.squares_rows <= 1:
        print("[ERROR] squares-rows must be >= 2")
        return 1

    inner_cols, inner_rows, square_size, used_meta = choose_effective_pattern(args)
    pattern_size = (inner_cols, inner_rows)

    if inner_cols <= 1 or inner_rows <= 1:
        print("[ERROR] inner-cols and inner-rows must both be > 1")
        return 1
    if square_size <= 0:
        print("[ERROR] square-size must be > 0")
        return 1
    if args.min_samples < 3:
        print("[ERROR] min-samples must be >= 3")
        return 1

    if used_meta is not None:
        print(f"[INFO] Loaded board metadata: {used_meta}")
    print(f"[INFO] Pattern inner corners (used for calibration): {inner_cols} x {inner_rows}")
    print(f"[INFO] Equivalent square count: {inner_cols + 1} x {inner_rows + 1}")
    print(f"[INFO] Square size: {square_size} mm")

    cap = open_camera(args.camera_index, args.width, args.height)
    if cap is None:
        print(f"[ERROR] Failed to open camera index {args.camera_index}")
        print("[TIP] Run: python calibrate/detect.py")
        return 1

    try:
        print(f"[INFO] Camera {args.camera_index} opened. Showing preview...")
        if not wait_for_confirm(cap, args.camera_index):
            print("[INFO] Cancelled by user before capture.")
            return 0

        out_root = (
            Path(args.output_root)
            if args.output_root is not None
            else Path(__file__).resolve().parent / f"runs_chess_{args.camera_id}"
        )
        run_dir = create_run_dir(out_root)
        print(f"[INFO] Run directory created: {run_dir}")

        session_info = {
            "camera_index": args.camera_index,
            "camera_id": args.camera_id,
            "pattern_squares_cols": inner_cols + 1,
            "pattern_squares_rows": inner_rows + 1,
            "pattern_inner_cols": inner_cols,
            "pattern_inner_rows": inner_rows,
            "square_size_mm": square_size,
            "min_samples": args.min_samples,
            "requested_size": [args.width, args.height],
            "board_meta_path": str(used_meta) if used_meta is not None else None,
        }
        (run_dir / "session_info.json").write_text(json.dumps(session_info, indent=2), encoding="utf-8")

        object_points, image_points, image_size, saved_paths = capture_samples(
            cap,
            run_dir,
            pattern_size,
            square_size,
        )

        if len(saved_paths) < args.min_samples:
            print(
                f"[ERROR] Only {len(saved_paths)} images captured, "
                f"but at least {args.min_samples} are required."
            )
            print(f"[INFO] Captured images remain in: {run_dir}")
            return 1

        if image_size is None:
            print("[ERROR] No valid capture was recorded.")
            return 1

        camera_matrix, dist_coeffs = calibrate_and_save(
            run_dir,
            object_points,
            image_points,
            image_size,
            args.camera_index,
            pattern_size,
            square_size,
            used_meta,
        )

        if args.show_undistorted:
            print("[INFO] Showing undistorted preview...")
            preview_undistortion(cap, camera_matrix, dist_coeffs)

        print(f"[DONE] All outputs saved under: {run_dir}")
        return 0
    finally:
        cap.release()
        cv2.destroyAllWindows()


if __name__ == "__main__":
    raise SystemExit(main())
